# Generated by Django 3.1.7 on 2021-03-08 22:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=26, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency_type', models.IntegerField(choices=[(1, 'Bitcoin'), (2, 'Ethereum')])),
                ('created', models.DateField()),
                ('processed', models.DateField()),
                ('state', models.IntegerField(choices=[(1, 'Unconfirmed'), (2, 'Confirmed'), (3, 'Rejected')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('email', models.CharField(error_messages={'unique': 'User with that email already exists'}, max_length=255, unique=True)),
                ('max_amount_per_transaction', models.DecimalField(decimal_places=18, max_digits=26, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='backendservice.transaction')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='backendservice.user')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='backendservice.user'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='target_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='backendservice.user'),
        ),
        migrations.CreateModel(
            name='EthereumWallet',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('private_key', models.CharField(max_length=64)),
                ('balance', models.DecimalField(decimal_places=18, default=0.0, max_digits=26, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backendservice.user')),
            ],
        ),
        migrations.CreateModel(
            name='BitcoinWallet',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('private_key', models.CharField(max_length=64)),
                ('balance', models.DecimalField(decimal_places=8, default=0.0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backendservice.user')),
            ],
        ),
    ]
