# Generated by Django 3.1.7 on 2021-03-10 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backendservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoinwallet',
            name='public_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ethereumwallet',
            name='public_key',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
