# Generated by Django 3.1.7 on 2021-03-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendservice', '0002_auto_20210310_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='signature',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
