# Generated by Django 3.1.7 on 2021-03-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendservice', '0003_transaction_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='source_user_id',
            new_name='source_user',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='target_user_id',
            new_name='target_user',
        ),
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='user_id',
            new_name='user',
        ),
    ]
