# Generated by Django 3.1.7 on 2021-03-11 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendservice', '0004_auto_20210311_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinwallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
