# Generated by Django 3.1.7 on 2021-03-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendservice', '0005_auto_20210311_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency_type',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum')], max_length=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('Unconfirmed', 'Unconfirmed'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Unconfirmed', max_length=11),
        ),
    ]
