# Generated by Django 3.1.7 on 2021-03-11 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backendservice', '0006_auto_20210311_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='processed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
